Fix libdl error
Fix error

/usr/bin/ld: CMakeFiles/worldserver.dir/Master.cpp.o: undefined reference to symbol 'dlerror@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line